
FROM --platform=linux/amd64 python:3.11-slim
ENV DEBIAN_FRONTEND=noninteractive

# Install build tools, python dev headers, audio library, and a full web browser for selenium
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    python3-dev \
    portaudio19-dev \
    git \
    curl \
    # Add browser for Selenium
    chromium \
    chromium-driver \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app


RUN pip3 install --upgrade pip setuptools wheel

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

RUN mkdir -p /opt/workspace
RUN mkdir -p /tmp && chmod 1777 /tmp

# Copy application code
COPY api.py .
COPY sources/ ./sources/
COPY prompts/ ./prompts/
COPY crx/ crx/
COPY llm_router/ llm_router/
COPY config.ini .

EXPOSE 8000

# Run the application
CMD ["python3", "api.py"]